name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
      
      - name: Set environment
        run: echo "JAVA_HOME=$JAVA_HOME_17" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: |
          pip install setuptools
          pip install buildozer==1.5.0
          pip install kivy==2.3.1
          pip install plyer
          pip install pillow
      
      - name: Build APK
        run: |
          echo "y" | buildozer android debug
        env:
          BUILDOZER_ANDROID_API: 33
          BUILDOZER_ANDROID_NDK_VERSION: 21e
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk